# Generated by Django 3.1.2 on 2021-04-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqudasite', '0015_auto_20210405_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
